# Generated by Django 2.2 on 2019-05-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190426_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='imb',
            field=models.URLField(blank='True'),
        ),
    ]
