# Generated by Django 2.2 on 2019-05-07 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_imb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='imb',
            new_name='img',
        ),
    ]
